### PR TITLE
lang-it.js

### PR DESCRIPTION
**Pull request by Macapple96**
Updated lang-it.js so the UI, "Movement", "Shapes" and "Colors" menus are properly translated.

### CODE REVIEW

**Comment by bromagosa** [comment]
Hi! Thanks for your contribution. I'm afraid this should go to Snap! though, as it contains many strings that are not used in BeetleBlocks. The translations for BeetleBlocks should only contain the extra strings that we add to the system, and all the rest should go to Snap! itself.

Check out this file for an example: https://github.com/ericrosenbaum/BeetleBlocks/blob/master/beetleblocks/lang-ca.js

**Comment by Macapple96** [comment]
Oh! Sorry! I'll filter out the Snap stuff and keep only Beetleblocks related translations!

**Comment by sfederici** [comment]
[lang-it.zip](https://github.com/ericrosenbaum/BeetleBlocks/files/2450864/lang-it.zip)
This is the beetleblocks-only translation. Please let me know if you find still something wrong.

**Comment by bromagosa** [comment]
I'm sorry it took me SO long. I had just forgotten about this!

Your translation is now integrated.

**Pull request closed without merging**
